[package]
name = "jarvis-alpha-innotec-planner"
version = "0.1.0"
authors = ["Jorrit Salverda <jorrit.salverda@gmail.com>"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0"
env_logger = "0"
log = "0"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros"] }
uuid = { version = "0", features = ["v4"] }
serde-xml-rs = "0"
websocket = "0"
regex = "1"
jarvis-lib = { git = "https://github.com/JorritSalverda/jarvis-lib", tag = "0.1.33" }