[package]
name = "jarvis-alpha-innotec-planner"
version = "0.1.0"
authors = ["Jorrit Salverda <jorrit.salverda@gmail.com>"]
edition = "2018"
include = ["src/**/*", "LICENSE", "README.md"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
log = "0.4.14"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.5", features = ["macros"] }
uuid = { version = "0.8", features = ["v4"] }
serde-xml-rs = "0.4"
websocket = "0.26"
regex = "1.5"
jarvis-lib = { git = "https://github.com/JorritSalverda/jarvis-lib", tag = "0.1.27" }