localTimeZone: Europe/Amsterdam
heatpumpTimeZone: Europe/Amsterdam
maximumHoursToPlanAhead: 12
minimalDaysBetweenDesinfection: 4
desinfectionLocalTimeSlots:
  Fri:
    - from: 7:00:00
      till: 19:00:00
      ifPriceBelow: 0.0
  Sat:
    - from: 7:00:00
      till: 19:00:00
      ifPriceBelow: 0.1
  Sun:
    - from: 7:00:00
      till: 19:00:00