loadProfile:
  sections:
    - durationSeconds: 7200
      powerDrawWatt: 2000
desinfectionLoadProfile:
  sections:
    - durationSeconds: 7200
      powerDrawWatt: 2000
    - durationSeconds: 1800
      powerDrawWatt: 8000
localTimeZone: Europe/Amsterdam
heatpumpTimeZone: Europe/Amsterdam
desiredTapWaterTemperature: 50.0
minHoursSinceLastDesinfection: 96
maxHoursSinceLastDesinfection: 240
jitterMaxMinutes: 10
enableBlockingWorstHeatingTimes: true