# Default values for jarvis-alpha-innotec-planner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronjob:
  schedule: '5 6,18 * * *'
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 2
  ttlSecondsAfterFinished: 3600

config:
  websocketHostIP: 127.0.0.1
  websocketHostPort: 8214
  websocketLoginCode: 999999
  configYaml: |
    planningStrategy: Consecutive
    plannableLocalTimeSlots:
      Mon:
        - from: 0:00:00
          till: 7:00:00
        - from: 23:00:00
          till: 0:00:00
      Tue:
        - from: 0:00:00
          till: 7:00:00
        - from: 23:00:00
          till: 0:00:00
      Wed:
        - from: 0:00:00
          till: 7:00:00
        - from: 23:00:00
          till: 0:00:00
      Thu:
        - from: 0:00:00
          till: 7:00:00
        - from: 23:00:00
          till: 0:00:00
      Fri:
        - from: 0:00:00
          till: 7:00:00
        - from: 23:00:00
          till: 0:00:00
      Sat:
        - from: 0:00:00
          till: 0:00:00
      Sun:
        - from: 0:00:00
          till: 0:00:00
    sessionDurationInSeconds: 7200
    localTimeZone: Europe/Amsterdam
    heatpumpTimeZone: UTC
    desinfectionDayOfWeek: Sun

logLevel: info

image:
  repository: jsalverda/jarvis-alpha-innotec-planner
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
