apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jarvis-alpha-innotec-planner.fullname" . }}
  labels:
    {{- include "jarvis-alpha-innotec-planner.labels" . | nindent 4 }}
data:
  websocket-host-ip: {{ .Values.config.websocketHostIP | quote }}
  websocket-host-port: {{ .Values.config.websocketHostPort | quote }}
  websocket-login-code: {{ .Values.config.websocketLoginCode | quote }}
  config.yaml: |
    {{- with .Values.config.configYaml }}
    {{- tpl . $ | nindent 4 }}
    {{- end }}