{{- if .Values.rbac.enable -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "jarvis-alpha-innotec-planner.fullname" . }}
  labels:
    {{- include "jarvis-alpha-innotec-planner.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "jarvis-alpha-innotec-planner.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "jarvis-alpha-innotec-planner.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}